version: "3.9"
services:
  orthanc:
    build:
      context: ./orthanc
      dockerfile: Dockerfile
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    restart: unless-stopped
    environment:
      - ORTHANC_NAME=${ORTHANC_NAME}
      - USERNAME=${USERNAME}
      - PW=${PW}
    volumes:
      - ${LOCAL_WORKSPACE}/orthanc_db/db-index:/var/lib/orthanc/db-index #cannot be saved to network mount
      - ${LOCAL_WORKSPACE}/orthanc_db/db:/var/lib/orthanc/db
  monailabel:
    build:
      context: ./monailabel
      dockerfile: Dockerfile
    command: >
      monailabel start_server 
      --app /app/monaibundle 
      --studies ${SERVER} 
      --conf models renalStructures_UNEST_segmentation 
      --conf use_pretrained_model false
      --conf skip_trainers true
      --conf preload false
    ports:
      - 8000:8000
    # IPC set to host
    ipc: 'host'
    net: 'host'
    ulimit: 
      memlock: 1
      stack: 67108864
    restart: unless-stopped
    environment:
      - http_proxy=  # need to be unset for docker to docker communication
      - MONAI_LABEL_DICOMWEB_USERNAME=${USERNAME}
      - MONAI_LABEL_DICOMWEB_PASSWORD=${PW}
      - MONAI_LABEL_DICOMWEB_SEARCH_FILTER=${SEARCH_FILTER}
      - MONAI_LABEL_DICOMWEB_READ_TIMEOUT=60.0
      - MONAI_LABEL_API_STR=
    volumes:
      - ${LOCAL_WORKSPACE}/../monai_models:/app/monaibundle/model  # store models
      - ${LOCAL_WORKSPACE}/monailabel_cache:/root/.cache/monailabel
      # - ${LOCAL_WORKSPACE}/dist-packages:/usr/local/lib/python3.10/dist-packages # uncomment to debug and fix monailabel