version: "3.9"
services:
  reverse-proxy:
    extends:
      file: common.yml
      service: reverse-proxy
    depends_on: [orthanc, monailabel]
  orthanc:
    extends:
      file: common.yml
      service: orthanc
  monailabel:
    extends:
      file: common.yml
      service: monailabel
    depends_on: [orthanc]
secrets:
  orthanc.json:
    file: orthanc/orthanc.json
