version: "3.9"
services:
  reverse-proxy:
    extends:
      file: common.yml
      service: reverse-proxy
  orthanc:
    extends:
      file: common.yml
      service: orthanc
    depends_on: [reverse-proxy]
  monailabel:
    extends:
      file: common.yml
      service: monailabel
    depends_on: [reverse-proxy, orthanc]
secrets:
  orthanc.json:
    file: orthanc/orthanc.json
