version: "3.9"
services:
  orthanc:
    extends:
      file: common.yml
      service: orthanc
  monailabel:
    extends:
      file: common.yml
      service: monailabel
    depends_on: [orthanc]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
secrets:
  orthanc.json:
    file: orthanc/orthanc.json
